Панюшкин Андрей Михайлович, гр. 6313, Л/Р №1
itsecd/ptm-1 pull request #1
Opened 2023-09-11 17:54 UTC by Santas7

Лабораторная работа номер 1
Взял за основу обычный код в 300 с небольшим строчек кода на языке программирования Python.
Затем проанализировал его и сделал несколько правок (а именно нашел 10 нарушений) в соответствии с PEP.

2023-09-13 12:12 UTC, alxmcs requested changes
Забыл упомянуть в задании - было бы неплохо прикладывать ссылку на репозиторий/гист/статью с туториалом в интернете/так далее, откуда был взят исходный код

2023-09-13 12:12 UTC, alxmcs commented on main.py
> +class Book:
Удалять код из скрипта([этот](https://github.com/itsecd/ptm-1/pull/1/commits/461e7e8f8c7323d9df7639212b3b84d2491573d8) коммит) мне кажется сомнительной идеей
1) это breaking change - ведь гипотетический некто может импортировать твои классы в свой проект, и удаление методов нарушит интеграцию
2) лаба про pep8, так что лучше причесать этот код, чем удалять

2023-09-13 12:57 UTC, Santas7 commented
а да про ссылку на код откуда я его взял ( у меня нету как бы ссылки, он валялся возможно в файлах компа где то там... )

2023-09-13 15:42 UTC, alxmcs requested changes
В части докстрингов нет описания параметров, в части - есть.
Также у части методов нет тайпхинтов возвращаемого значения.

История обретения кода звучит крайне сомнительно, но да ладно.

2023-09-15 06:05 UTC, alxmcs requested changes
Доделай уже нормально эту несчастную лабораторную для дошкольников

2023-09-15 06:05 UTC, alxmcs commented on main.py
> +        import json
Почему это харам:
* PEP8: "readability counts".  Ты зависимости модуля рассовал по куче функций. Теперь этот код сложнее читать и анализировать.
* Несмотря на то, что импорт выполнится единожды при первом обращении к функции, он не мгновенен.
* Ошибку импорта модуля удобнее получить при запуске модуля сразу, а не при вызове специфического метода/функции.
*  Какие проблемы ты огребешь, если будешь заниматься такими вещами в многопоточном коде - `пикча про внутри арбуз какой.jpg`

В общем, все импорты поднять в начало модуля

2023-09-15 06:05 UTC, alxmcs commented on main.py
> +        :param author:
Здесь и далее по коду: 
Написать описание параметра не судьба?

2023-09-15 08:29 UTC, alxmcs requested changes
Если ты думаешь, что это я над тобой издеваюсь, то это не так - это ты надо мной издеваешься

2023-09-15 08:29 UTC, alxmcs commented on main.py
> +        '''
Почему тут одинарные кавычки, а в других докстрингах - двойные?

2023-09-15 08:29 UTC, alxmcs commented on main.py
> +        '''
Почему тут одинарные кавычки, а в остальных докстрингах - двойные?

2023-09-15 08:29 UTC, alxmcs commented on main.py
> +        '''
Почему тут одинарные кавычки, а в остальных докстрингах - двойные?

2023-09-15 08:29 UTC, alxmcs commented on main.py
> +        '''
Почему тут одинарные кавычки, а в других докстрингах - двойные?

2023-09-15 08:29 UTC, alxmcs commented on main.py
> +        '''
Почему тут одинарные кавычки, а в других докстрингах - двойные?

2023-09-15 08:29 UTC, alxmcs commented on main.py
> +        '''
Почему тут одинарные кавычки, а в других докстрингах - двойные?

2023-09-15 08:29 UTC, alxmcs commented on main.py
> +        '''
Почему тут одинарные кавычки, а в других докстрингах - двойные?

2023-09-15 08:29 UTC, alxmcs commented on main.py
> +        '''
Почему тут одинарные кавычки, а в других докстрингах - двойные?

2023-09-15 08:29 UTC, alxmcs commented on main.py
> +        '''
Почему тут одинарные кавычки, а в других докстрингах - двойные?

2023-09-15 08:29 UTC, alxmcs commented on main.py
> +class Universal_file_reading:
Почитай внимательно правила именования классов в РЕР8

2023-09-15 09:08 UTC, Santas7 commented
Изменил ковычки на везде одинарные, изменил название класса (понял что по PEP8 именование класса должно начинаться с заглавной буквы и не должно содержать символов нижнего подчеркивания)

2023-09-15 10:47 UTC, alxmcs requested changes

2023-09-15 10:47 UTC, alxmcs commented on main.py
> +import time
Проглядел в прошлых ревью - в секции с зависимостями обычно сначала идут директивы import, потом from в алфавитном порядке

2023-09-15 10:47 UTC, alxmcs commented on main.py
> +from PIL.Image import Image
Как думаешь, который из `Image` в итоге будет импортнут в твоем коде? Этот?

2023-09-15 10:47 UTC, alxmcs commented on main.py
> +from PIL import Image
Или вот этот?

2023-09-15 11:43 UTC, Santas7 commented
я исправил код - надеюсь сейчас все в порядке)

2023-09-15 11:44 UTC, alxmcs approved these changes
Зачтено

2023-09-15 11:44 UTC, closed without merging