Нестеренко Адрей, 6312-100503D, лаб. 1
itsecd/ptm-1 pull request #10
Opened 2023-09-17 09:33 UTC by MagGoldi

Для лабораторной работы использовал материал по курсу прикладное программирование. Реализация задачи оставляет желать лучшего...

2023-09-20 09:07 UTC, alxmcs requested changes
Общие замечания:
1) Тебя никак не насторожило вот это - ![image](https://github.com/itsecd/ptm-1/assets/70561974/e50e878e-1b82-4cc5-b011-9aa23e20943d) ![image](https://github.com/itsecd/ptm-1/assets/70561974/a98c5d37-f9c7-43e3-8ed8-f05920397b5a)? Рекомендую завести в репозитории .gitignore и прописать нем папку с 800+ csv файлами

2) Названия модулей `scrnipt_1` и т.д. не сильно коррелируют с принципом `readability counts`. Их надо переименовать так, чтобы их функционал был более-менее ясен из их названий.

2023-09-22 12:09 UTC, MagGoldi commented
1) Добавил папку в .gitignore, изменения игнорируются, но когда удалил файлы изменения внеслись(в последнем коммите).Не баг а фича .В социальной сети интернет ответа не нашел, надеюсь на вашу помощь.
2) Изменил все модули и названия файлов, не знаю приблизило ли это к дзену _**readability counts**_ . Но как сказал великий предприниматель "_Сомнительно, но окэй..._"

2023-09-22 12:11 UTC, alxmcs requested changes
Зачтено

2023-09-22 12:12 UTC, alxmcs approved these changes

2023-09-22 12:12 UTC, closed without merging