6312-100503D Челаев Петр Лаб. № 1
itsecd/ptm-1 pull request #33
Opened 2023-10-01 17:01 UTC by PripyatskyPrometheus

Первая моя лабораторная по Технологиям и методам программирования. Состоит из двух файлов, в которых хранятся две совершенно разные лабы совершенно разных людей. Их коды были отредактированы в соответствии с требованиями PEP8.
Ссылки на исходные коды:
https://github.com/Matvey6M6/Application-programming-Lab1/blob/main/Lab1.py
https://github.com/MagGoldi/isb-3/blob/4a1f742f467b4b80ae3a4e11350335687c3b77ba/main.py

2023-10-02 11:12 UTC, alxmcs requested changes

2023-10-02 11:12 UTC, alxmcs commented on Lab_1_file_one.py
> +headers = {"User-Agent": "Mozilla/5.0"}
Константы модуля идут после импортов и именуются капсом

2023-10-02 11:12 UTC, alxmcs commented on Lab_1_file_two.py
> +        # проверка правильности введенной желаемой длины ключа
Вместо комментариев в  коде лучше написать докстринг

2023-10-02 11:12 UTC, alxmcs commented on Lab_1_file_one.py
> +    url = "https://www.livelib.ru/reviews/"
Это и две строки ниже лучше вынести в константы

2023-10-02 17:33 UTC, PripyatskyPrometheus commented
Сделано. Вроде бы ничего не пропустил

2023-10-03 07:28 UTC, alxmcs approved these changes
Зачтено

2023-10-03 07:28 UTC, closed without merging