Уваров Никита Дмитриевич 6313-100503D 1Лаба
itsecd/ptm-1 pull request #39
Opened 2023-10-08 14:48 UTC by Rifinn-crypto

Код взят отсюда: https://www.programmersought.com/article/63545382253/

2023-10-09 08:59 UTC, alxmcs requested changes

2023-10-09 08:59 UTC, alxmcs commented on Lab5/main.py
Исправить имя модуля на соответствующее его функционалу

2023-10-09 08:59 UTC, alxmcs commented on Lab5/main.py
> +WriteStep = 15
Именование констант привести в соответствие с РЕР (здесь и далее по коду)

2023-10-09 08:59 UTC, alxmcs commented on Lab5/main.py
> +def bezier(p1, p2, t):
Добавить тайпхинты (здесь и далее по коду)

2023-10-09 08:59 UTC, alxmcs commented on Lab5/main.py
> +    :param p1,
Добавить описания к параметрам в докстрингах (здесь и далее по коду)

2023-10-25 14:48 UTC, alxmcs requested changes

2023-10-25 14:48 UTC, alxmcs commented on Lab5/get_picture.py
> +Yh = 0
Не забываем ,что константы согласно РЕР пишутся капсом

2023-10-25 14:48 UTC, alxmcs commented on Lab5/get_picture.py
> +                :param y4"""
Здесь и далее по коду - надо бы поправить эту странную лестницу и дописать таки пояснения к параметрам, раз они перечислены в докстринге

2023-10-25 14:48 UTC, alxmcs commented on Lab5/get_picture.py
> +te.tracer(10)
Исполняемую часть, полагаю, стоит убрать под `if __name__=="__main__":`

2023-10-25 15:01 UTC, Rifinn-crypto commented
Какой-то глюк произошел с комитами.. Сейчас все появились изменения..

2023-10-26 13:24 UTC, alxmcs approved these changes
Зачтено

2023-10-26 13:25 UTC, closed without merging