6213-100503D Ненашев Дмитрий Михайлович Лаб.1
itsecd/ptm-1 pull request #49
Opened 2023-10-16 23:42 UTC by neygenius

Код взял отсюда: 
https://github.com/Dmitrii14/python_var4/tree/e3a628b334273becaf527b6e93129bb336ce021b/Lab1

2023-10-17 09:10 UTC, alxmcs requested changes

2023-10-17 09:10 UTC, alxmcs commented on main.py
> +    Проверяет существование рабочей директории
Судя по коду, только проверкой дело не ограничивается

2023-10-17 09:10 UTC, alxmcs commented on main.py
> +        if not os.path.isdir("dataset"):
Фу, захардкоженная строка

2023-10-17 09:10 UTC, alxmcs commented on main.py
> +        os.mkdir(f"dataset/{name}")
И тут

2023-10-17 09:10 UTC, alxmcs commented on main.py
> +    :param name: название изображения
Наверное, это все-таки не "название изображения", а поисковый запрос.
Словосочетание "название изображения" скорее синонимично имени сохраняемого файла, а не той роли, которую выполняет этот параметр в коде.

2023-10-18 09:57 UTC, alxmcs requested changes
Я заметил, что в предыдущем ревью не отметил в ремарках, что объем кода меньше количества, указанного в условии лабы. Надо 300+ строк. Тут 76.

2023-10-22 20:06 UTC, neygenius commented
_Ссылка на новый код_:
https://github.com/megapro17/zvukdown

2023-10-23 07:59 UTC, alxmcs commented
Если все необходимые изменения внесены, то ![image](https://github.com/itsecd/ptm-1/assets/70561974/c028e68e-1614-43ab-86ef-0272bfe8bceb)

2023-10-25 12:30 UTC, alxmcs approved these changes
Зачтено

2023-10-25 14:48 UTC, closed without merging