Богачев Матвей 6311
itsecd/ptm-1 pull request #50
Opened 2023-10-19 12:26 UTC by Matosik

1. Нашел код, который не соответствовал формату pep8
 ̷2̷.̷ ̷с̷к̷а̷ч̷а̷л̷ ̷a̷u̷t̷o̷p̷e̷p̷8̷ ̷и̷ ̷в̷с̷ё̷ ̷п̷о̷д̷о̷г̷н̷а̷л̷ ̷п̷о̷д̷ ̷ф̷о̷р̷м̷а̷т̷ ̷p̷e̷p̷8̷
2. Прочитал всю документацию pep
3. Прошелся по каждой строке кода, найденного на просторах github, параллельно меня формат кода под стандарты pep8

2023-10-23 09:53 UTC, alxmcs requested changes

2023-10-23 09:53 UTC, alxmcs commented on without format pep8/gather_build_data.py
> +GRADLE_SYNC_END = re.compile(r"^([\d\-:,\s]+) \[\d+\].* Gradle sync (\w+) in ([\d\s\w]+)\n$")
Константы переместить после импортов

2023-10-23 09:53 UTC, alxmcs commented on without format pep8/gather_build_data.py
> +    # Pass an argument to look in a different place instead
Превратить в докстринг

2023-10-23 09:53 UTC, alxmcs commented on without format pep8/gather_build_data.py
> +    # with methods to extract the processed test_data in more convenient formats
Превратить в докстринг

2023-10-23 14:08 UTC, alxmcs requested changes

2023-10-23 14:08 UTC, alxmcs commented on without format pep8/gather_build_data.py
> +GRADLE_SYNC_END = re.compile(r"^([\d\-:,\s]+) \[\d+\].* Gradle sync (\w+) in ([\d\s\w]+)\n$")
![image](https://github.com/itsecd/ptm-1/assets/70561974/c14a0ed6-27b8-46a5-920e-ca68e84a876f)

2023-10-24 14:25 UTC, Matosik commented on without format pep8/gather_build_data.py
> +GRADLE_SYNC_END = re.compile(r"^([\d\-:,\s]+) \[\d+\].* Gradle sync (\w+) in ([\d\s\w]+)\n$")
Константы перемещены после импортов 💀

2023-10-24 14:26 UTC, alxmcs approved these changes

2023-10-24 14:26 UTC, closed without merging