Маясов Данила 6311-100503D 1 лаб. ТМП
itsecd/ptm-1 pull request #55
Opened 2023-10-27 14:42 UTC by danyala1

2023-10-31 07:51 UTC, alxmcs requested changes
1) Как-то уже позорно на третьем курсе коммитить через веб-интерфейс гитхаба.
2) Условие сдачи лабы - объем кода не менее 300 строк. Я вижу 205.

2023-11-08 13:19 UTC, alxmcs requested changes
![image](https://github.com/itsecd/ptm-1/assets/70561974/8088a07d-e4c0-49bb-bc5d-512c839f43fc)
А где рефакторинг?

2023-11-08 13:22 UTC, danyala1 commented
Я написал, что только добавил, сейчас сделаю рефакторинг.
Ссылки с источниками кода:  https://github.com/marcoemrich/Refactoring-Katas/tree/master/Yahtzee/python
https://github.com/marcoemrich/Refactoring-Katas/blob/master/Tennis/python/tennis.py

2023-11-08 16:26 UTC, alxmcs approved these changes
Зачтено

2023-11-08 16:26 UTC, closed without merging